# Generated by Django 4.1.5 on 2023-04-05 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createservice',
            name='image',
            field=models.ImageField(default='None', upload_to='img/service_provider'),
        ),
        migrations.AddField(
            model_name='createservice',
            name='salon_color',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='createservice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='last_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='location',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='opening_and_closing_time',
            field=models.CharField(default='00:00', max_length=200),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='salon_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='salon_services',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
