# Generated by Django 4.1.5 on 2023-01-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createservice',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
