# Generated by Django 4.1.4 on 2023-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_alter_createservice_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='createservice',
            name='image',
            field=models.ImageField(default=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='createservice',
            name='salon_color',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
