# Generated by Django 4.1.4 on 2023-01-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_createservice_image_createservice_salon_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createservice',
            name='salon_color',
            field=models.CharField(max_length=200),
        ),
    ]
