# Generated by Django 4.1.5 on 2023-02-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0004_alter_createservice_salon_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createservice',
            name='opening_and_closing_time',
            field=models.CharField(max_length=200),
        ),
    ]
