# Generated by Django 4.1.5 on 2023-02-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_alter_createservice_opening_and_closing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createservice',
            name='first_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='image',
            field=models.ImageField(default=True, unique=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='last_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='location',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='opening_and_closing_time',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='salon_color',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='salon_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='createservice',
            name='salon_services',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
