# Generated by Django 4.1.5 on 2023-02-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0006_alter_createservice_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateService',
        ),
    ]
