# Generated by Django 4.1.5 on 2023-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_provider', '0007_delete_createservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, unique=True)),
                ('last_name', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('salon_name', models.CharField(max_length=200, unique=True)),
                ('salon_services', models.TextField(max_length=200, unique=True)),
                ('opening_and_closing_time', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(default=True, unique=True, upload_to=None)),
                ('salon_color', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
