# Generated by Django 4.1.5 on 2023-02-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0009_alter_createservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createservice',
            name='image',
            field=models.ImageField(default=True, unique=True, upload_to='service_provider/'),
        ),
    ]
